### ISSUE TITLE
wordpress 5.4 core samesite

### ISSUE THREAD

**Issue by beriox** [Ayesh/WordPress-SameSite#1]
Hello Ayesh! Good idea, your extension, see also here (maybe you already know):
https://core.trac.wordpress.org/ticket/37000#comment:20
it seems that the core team is going to integrate samesite support in wp 5.4
with native php 7.3 functionalities and with the previous modality too...
Bye, Stefano

**Comment by Ayesh** [comment]
Thank you @beriox. I'm happy to see the WP core team taking interest in this. Google Chrome 80+ assumes cookies to be SameSite=Lax unless otherwise specified, so this plugin will be obsolete if the trend catches up. Thanks for your input, I appreciate it a lot.
